using AutoGen;
using AutoGen.Core;
using AutoGen.OpenAI;
using System.Net.Http;
using System.Text;
using System.Text.Json;

namespace AIDataPlatform.Services.AI
{
    /// <summary>
    /// A specialized agent that uses Perplexity AI for research capabilities
    /// </summary>
    public class PerplexityResearchAgent : IAgent
    {
        private readonly string _name;
        private readonly string _systemMessage;
        private readonly string _apiKey;
        private readonly string _model;
        private readonly HttpClient _httpClient;
        private readonly bool _verbose;

        /// <summary>
        /// Gets the name of the agent
        /// </summary>
        public string Name => _name;

        /// <summary>
        /// Initializes a new instance of the PerplexityResearchAgent class
        /// </summary>
        /// <param name="name">The name of the agent</param>
        /// <param name="systemMessage">The system message defining the agent's behavior</param>
        /// <param name="apiKey">The Perplexity AI API key</param>
        /// <param name="model">The Perplexity AI model to use</param>
        /// <param name="verbose">Whether to output verbose logs</param>
        public PerplexityResearchAgent(
            string name,
            string systemMessage,
            string apiKey,
            string model = "sonar",
            bool verbose = false)
        {
            _name = name;
            _systemMessage = systemMessage;
            _apiKey = apiKey;
            _model = model;
            _verbose = verbose;
            _httpClient = new HttpClient();
            _httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {apiKey}");
        }

        /// <summary>
        /// Sends an introduction message to the chat
        /// </summary>
        /// <param name="introduction">The introduction message</param>
        /// <param name="groupChat">The group chat</param>
        public void SendIntroduction(string introduction, GroupChat groupChat)
        {
            var introMessage = new TextMessage(Role.Assistant, introduction);
            groupChat.SendIntroduction(introMessage);
        }

        /// <summary>
        /// Sends a message to be processed by the Perplexity AI API
        /// </summary>
        /// <param name="messages">The messages to be processed</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>The response from Perplexity AI</returns>
        public Task<IMessage> GenerateReplyAsync(
            IReadOnlyList<IMessage> messages,
            CancellationToken cancellationToken = default)
        {
            return GenerateReplyAsync(messages, null, cancellationToken);
        }

        /// <summary>
        /// Sends a message to be processed by the Perplexity AI API with options
        /// </summary>
        /// <param name="messages">The messages to be processed</param>
        /// <param name="options">Generation options</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>The response from Perplexity AI</returns>
        public async Task<IMessage> GenerateReplyAsync(
            IEnumerable<IMessage> messages,
            GenerateReplyOptions? options,
            CancellationToken cancellationToken = default)
        {
            try
            {
                // Convert messages to a list to work with
                var messagesList = messages.ToList();

                // Convert AutoGen messages to Perplexity AI format
                var perplexityMessages = ConvertToPerplexityMessages(messagesList);

                // Create the request to Perplexity AI
                var requestBody = new
                {
                    model = _model,
                    messages = perplexityMessages
                };

                var json = JsonSerializer.Serialize(requestBody);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                
                // Send the request to Perplexity AI
                var response = await _httpClient.PostAsync(
                    "https://api.perplexity.ai/chat/completions",
                    content,
                    cancellationToken);

                response.EnsureSuccessStatusCode();
                
                var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
                var responseObject = JsonSerializer.Deserialize<PerplexityResponse>(responseContent);

                if (responseObject?.choices == null || responseObject.choices.Count == 0)
                {
                    return new TextMessage(Role.Assistant, "No response was generated by Perplexity AI.", from: _name);
                }

                // Get the content from the response
                var messageContent = responseObject.choices[0].message.content;
                
                if (_verbose)
                {
                    Console.WriteLine($"[{_name}] Response: {messageContent}");
                }

                // Return the response as a message
                return new TextMessage(Role.Assistant, messageContent, from: _name);
            }
            catch (Exception ex)
            {
                if (_verbose)
                {
                    Console.WriteLine($"[{_name}] Error: {ex.Message}");
                    Console.WriteLine(ex.StackTrace);
                }

                return new TextMessage(
                    Role.Assistant,
                    $"I apologize, but I encountered an error while researching: {ex.Message}");
            }
        }

        /// <summary>
        /// Converts AutoGen messages to the format expected by Perplexity AI
        /// </summary>
        /// <param name="messages">The messages to convert</param>
        /// <returns>The converted messages</returns>
        private List<object> ConvertToPerplexityMessages(IReadOnlyList<IMessage> messages)
        {
            // Initialize the result with the system message
            var result = new List<object>
            {
                new { role = "system", content = _systemMessage }
            };

            // Use LINQ to transform the messages with explicit anonymous type
            var transformedMessages = messages.Select(message => 
            {
                string role = message.From?.ToLower();
        
                // Perplexity only accepts system, user, and assistant roles
                if (role != "system" && role != "user" && role != "assistant")
                {
                    role = "user";
                }
        
                return new { role, content = message.GetContent() };
            });


            // Add the transformed messages to the result
            result.AddRange(transformedMessages);

            return result;
        }

        /// <summary>
        /// Class to deserialize Perplexity AI API responses
        /// </summary>
        private class PerplexityResponse
        {
            public List<PerplexityChoice> choices { get; set; }
        }

        /// <summary>
        /// Class to deserialize Perplexity AI API response choices
        /// </summary>
        private class PerplexityChoice
        {
            public PerplexityMessage message { get; set; }
        }

        /// <summary>
        /// Class to deserialize Perplexity AI API response messages
        /// </summary>
        private class PerplexityMessage
        {
            public string role { get; set; }
            public string content { get; set; }
        }
    }
}