using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.SemanticKernel;
using System.ComponentModel;

namespace AIDataPlatform.Plugins
{
    /// <summary>
    /// A Semantic Kernel plugin that provides research capabilities using Perplexity AI
    /// </summary>
    public class PerplexityResearchPlugin
    {
        private readonly string _apiKey;
        private readonly string _model;
        private readonly HttpClient _httpClient;

        /// <summary>
        /// Initializes a new instance of the PerplexityResearchPlugin class
        /// </summary>
        /// <param name="configuration">Application configuration providing the Perplexity AI settings</param>
        public PerplexityResearchPlugin(IConfiguration configuration)
        {
            var settings = configuration.GetSection("PerplexityAI");
            _apiKey = settings["ApiKey"];
            _model = settings.GetValue<string>("Model") ?? "sonar";
            _httpClient = new HttpClient();
            _httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {_apiKey}");
        }

        /// <summary>
        /// Researches a query using Perplexity AI
        /// </summary>
        /// <param name="query">The query to research</param>
        /// <param name="systemMessage">Optional system message to guide the research</param>
        /// <param name="context">The kernel execution context</param>
        /// <returns>The research results</returns>
        [KernelFunction("search_web")]
        [Description("Searching the web using Perplexity AI")]
        public async Task<string> ResearchAsync(
            [Description("The query to research")]
            string query,
            [Description("Optional system message to guide the research")]
            string? systemMessage = null,
            CancellationToken cancellationToken = default)
        {
            try
            {
                if (string.IsNullOrEmpty(systemMessage))
                {
                    systemMessage = "You are a research assistant. Provide comprehensive, accurate, and well-structured information on the given query. Include relevant facts, data, and insights. Always cite your sources when possible.";
                }

                // Create the messages for Perplexity API
                var perplexityMessages = new List<object>
                {
                    new { role = "system", content = systemMessage },
                    new { role = "user", content = query }
                };

                // Create the request to Perplexity AI
                var requestBody = new
                {
                    model = _model,
                    messages = perplexityMessages
                };
                
                var json = JsonSerializer.Serialize(requestBody);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                
                // Send the request to Perplexity AI
                var response = await _httpClient.PostAsync(
                    "https://api.perplexity.ai/chat/completions",
                    content,
                    cancellationToken);

                response.EnsureSuccessStatusCode();
                
                var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
                var responseObject = JsonSerializer.Deserialize<PerplexityResponse>(responseContent);

                if (responseObject?.choices == null || responseObject.choices.Count == 0)
                {
                    return "No response was generated by Perplexity AI.";
                }

                // Get the content from the response
                var messageContent = responseObject.choices[0].message.content;

                return messageContent;
            }
            catch (Exception ex)
            {
                return $"I apologize, but I encountered an error while researching: {ex.Message}";
            }
        }

        /// <summary>
        /// Class to deserialize Perplexity AI API responses
        /// </summary>
        private class PerplexityResponse
        {
            public List<PerplexityChoice> choices { get; set; }
        }

        /// <summary>
        /// Class to deserialize Perplexity AI API response choices
        /// </summary>
        private class PerplexityChoice
        {
            public PerplexityMessage message { get; set; }
        }

        /// <summary>
        /// Class to deserialize Perplexity AI API response messages
        /// </summary>
        private class PerplexityMessage
        {
            public string role { get; set; }
            public string content { get; set; }
        }
    }
}